# Defining the schema version. In most cases, it's best to use the latest supported version.
version: "3.7"

# Defining the App Service from this command
# docker run -dp 3000:3000 \
#   -w /app -v "$(pwd):/app" \
#   --network todo-app \
#   -e MYSQL_HOST=mysql \
#   -e MYSQL_USER=root \
#   -e MYSQL_PASSWORD=secret \
#   -e MYSQL_DB=todos \
#   node:12-alpine \
#   sh -c "yarn install && yarn run dev"

# Defining the Mysql Service from this command:
# docker run -d \
#   --network todo-app --network-alias mysql \
#   -v todo-mysql-data:/var/lib/mysql \
#   -e MYSQL_ROOT_PASSWORD=secret \
#   -e MYSQL_DATABASE=todos \
#   mysql:5.7
services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3005:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: